---
# ansible/roles/windows_setup/tasks/main.yml

- name: Install IIS
  ansible.windows.win_feature:
    name: Web-Server
    state: present

- name: Ensure IIS service is running
  ansible.windows.win_service:
    name: W3SVC
    state: started
