- name: Install IIS
  win_feature:
    name: Web-Server
    state: present

- name: Create a test HTML page
  win_copy:
    content: "<h1>Hello from Ansible on Windows!</h1>"
    dest: C:\inetpub\wwwroot\index.html
