- name: Monthly Windows patching
  hosts: windows
  gather_facts: no
  tasks:
    - name: Apply all available Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes

- name: Monthly Linux patching
  hosts: linux
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: dist
