- name: Monthly Windows patching
  hosts: windows
  gather_facts: false
  tasks:
    - name: Apply all available Windows Updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true

- name: Monthly Linux patching
  hosts: linux
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
