- name: Site entrypoint
  hosts: all
  gather_facts: false

  roles:
    - windows_setup

  tasks:
    - name: Include firewall hardening
      ansible.builtin.include_tasks: ../policies/windows/firewall.yml

    - name: Include password policy
      ansible.builtin.include_tasks: ../policies/windows/password_policy.yml
