# ansible/playbooks/windows-servers.yml
- name: Provision Windows servers
  hosts: windows
  gather_facts: false

  roles:
    - role: common
    - role: browsers
    - role: editors
    - role: devtools

  tasks:
    # Reboot if a previous task set a flag (e.g., reboot_needed: true)
    - name: Reboot if needed
      ansible.windows.win_reboot:
      when: reboot_needed | default(false)

    # Post-check: verify common binaries are present
    - name: Verify binaries exist
      ansible.windows.win_shell: 'cmd /c where {{ item }}'
      loop:
        - git.exe
        - python.exe
        - code.exe
        - brave.exe
        - chrome.exe
      register: where_out
      changed_when: false
