---
# Ensure env/dept/owner/app tags conform to approved values
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Org.Azure.Tags.AllowedValues
  displayName: Tag values must be from approved lists
  severity: Error
spec:
  # Only evaluate resources that support tags
  with:
    - PSRule.Rules.Azure#Azure.Resource.SupportsTags
  condition:
    allOf:
      - field: 'tags.env'
        in:
          - prod
          - dev
          - test
      - field: 'tags.dept'
        in:
          - IT
          - HR
          - Finance
      - field: 'tags.owner'
        in:
          - 'Server Team'
          - 'Application Team'
          - 'Web Team'
      - field: 'tags.app'
        in:
          - 'VS Code'
          - 'Net App'
          - 'CommVault'
