# trigger:
# - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'YourServiceConnectionName' # The name of your Azure service connection
  resourceGroupName: 'MyResourceGroup'
  location: 'eastus'
  templateFile: 'infrastructure-as-a-code-sandbox/bicep/templates/main.bicep'
  parametersFile: 'infrastructure-as-a-code-sandbox/bicep/templates/main.bicepparam'
  psRuleBaselineFile: 'compliance/custom-baseline.yml'

stages:
- stage: Deploy
  jobs:
  - job: ARMDeploy
    displayName: 'Deploy Azure Resources'
    steps:
    - script: |
        npm install -g @microsoft/ps-rule-cli
      displayName: 'Install PSRule CLI'
    - checkout: self
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        azureSubscription: $(azureSubscription)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: $(templateFile)
        csmParametersFile: $(parametersFile)
        deploymentMode: 'Incremental'

    - script: |
        ps-rule -f $(psRuleBaselineFile) -o azure-pipelines-summary $(templateFile)
      displayName: 'Run PSRule Compliance Check'
