name: Deploy Azure Resource Group Bicep File

on:
  push:
    paths:
      - '**/*.bicepparam'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep using .bicepparam file
      uses: azure/bicep-deploy@v1
      with:
        scope: subscription
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
        location: eastus
        template-file: infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicep
        parameters-file: infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicepparam
