name: Deploy Azure Resource Group Bicep File

on:
  push:
    paths:
      - '**/*.bicepparam'  # Trigger only when .bicepparam files are pushed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep using .bicepparam file
        run: |
          az deployment sub create \
            --location eastus \
            --template-file ./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicep \
            --parameters @./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicepparam
