name: Deploy Bicep to Subscription

on:
  push:
    paths:
      - '**/*.bicepparam'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep using .bicepparam
        uses: azure/bicep-deploy@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          bicep-file: ./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicep
          parameter-file: ./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicepparam
          type: subscription  # 👈 required for az deployment sub create
