name: Deploy Azure Resource Group Bicep File

on:
  push:
    paths:
      - '**/*.bicepparam'  # Trigger when .bicepparam files are updated
  workflow_dispatch:        # Manual trigger support

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build .bicepparam to JSON
        run: |
          az bicep build-params \
            --file ./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicepparam \
            --outfile ./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.parameters.json

      - name: Deploy Bicep using compiled parameters
        run: |
          az deployment sub create \
            --location eastus \
            --template-file ./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicep \
            --parameters @./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.parameters.json
