name: Deploy Azure virtual machine Bicep file

on:
  workflow_dispatch:        # keep manual trigger
  push:
    branches: [ "main" ]     # or "main" or both
    paths:
      - 'infrastructure-as-a-code-sandbox/bicep/templates/create-virtual-machine/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # If you use OIDC instead of a JSON secret, use azure/login@v2 with permissions:
      # permissions:
      #   id-token: write
      #   contents: read
      # - name: Log into Azure (OIDC)
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Log into Azure (service principal JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId:     ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName:  ${{ secrets.AZURE_RG }}
          template:           ./infrastructure-as-a-code-sandbox/bicep/template/create-virtual-machine/main.bicep
          # Point directly to the .bicepparam file:
          parameters:         ./infrastructure-as-a-code-sandbox/bicep/template/create-virtual-machine/main.bicepparam
          deploymentName:     vm-deploy-${{ github.run_number }}
          failOnStdErr:       false
          # Remove scope when using resourceGroupName
          # scope: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION }}/resourceGroups/${{ secrets.AZURE_RG }}
