name: Deploy Azure Resource Group via Bicep

on:
  push:
    paths:
      - 'infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/**'
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy RG template
        uses: azure/bicep-deploy@v1
        with:
          type: deployment
          operation: create
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          resource-group-name: ${{ secrets.AZURE_RG }}
          template-file: ./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicep
          parameters-file: ./infrastructure-as-a-code-sandbox/bicep/templates/create-resource-group/main.bicepparam
          location: eastus
