name: Deploy VM (Bicep) and Clean Params

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure-as-a-code-sandbox/bicep/templates/create-virtual-machine/**'

permissions:
  contents: write
  id-token: write

jobs:
  deploy-and-clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure (service principal JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Pick the latest *.bicepparam in the folder, excluding "main.bicepparam"
      - name: Select latest .bicepparam
        id: pick
        shell: bash
        run: |
          set -euo pipefail
          PARAM_DIR="infrastructure-as-a-code-sandbox/bicep/templates/create-virtual-machine"

          # list newest first, exclude main.bicepparam if it exists
          latest=$(ls -t "$PARAM_DIR"/*.bicepparam 2>/dev/null | grep -vE '/main\.bicepparam$' | head -n1 || true)

          if [ -z "${latest:-}" ]; then
            echo "No transient .bicepparam files found. Nothing to deploy."
            echo "skip=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "param_file=$latest" >> "$GITHUB_OUTPUT"
          echo "skip=false" >> "$GITHUB_OUTPUT"
          echo "Selected param file: $latest"

      - name: Deploy Bicep (resource group scope)
        if: steps.pick.outputs.skip == 'false'
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId:     ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName:  ${{ secrets.AZURE_RG }}
          template:           ./infrastructure-as-a-code-sandbox/bicep/templates/create-virtual-machine/main.bicep
          parameters:         ${{ steps.pick.outputs.param_file }}
          deploymentName:     vm-deploy-${{ github.run_number }}
          failOnStdErr:       false

      # Clean up ONLY the param file that was just used
      - name: Cleanup selected param file and push
        if: steps.pick.outputs.skip == 'false' && success()
        shell: bash
        run: |
          set -euo pipefail
          file="${{ steps.pick.outputs.param_file }}"
          if [ -f "$file" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git rm -f "$file"
            git commit -m "cleanup: remove transient ${file##*/} after successful deploy"
            git push
          else
            echo "Selected param file already gone: $file"
          fi
